[package]
name = "bencher"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.0"
rayon = "1.2.1"
num_cpus = "1.12.0"
fnv = "1.0.6"
dashmap = { path = ".." }

[[bench]]
name = "dashmap"
harness = false
