name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run miri
      run: ./miri.sh
